huge credit to https://www.youtube.com/watch?v=doDUihpj6ro&t=4932s for teaching us how to step by step

In [ ]:
"""
Filename: lstm_training.py
Author: Minh Long Vu
Date: 2026-07-30
Description: This file scrip is insteded to take the samples for training the LSTM
"""

__author__ = "Minh Long Vu"
__license__ = "GPL"
__email__ = "minhlongvu626@gmail.com"
__status__ = "Prototype"

In [1]:
import os 
import numpy as np
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

In [ ]:
dir = "./actions" # CHANGE YOUR PATH HERE
label_map = [label for label in os.listdir(dir)]

['any', 'click', 'fire', 'gun_pose', 'open_palm']

In [ ]:
data, labels, label_map = [], [],[]
for index, act in enumerate(os.listdir(dir)):
    label_map.append(act)
    for vid in os.listdir(f"{dir}/{act}"):
        vid_frames = []
        for frame in os.listdir(f"{dir}/{act}/{vid}"):
            frame_path = f"{dir}/{act}/{vid}/{frame}"
            frame_data = np.load(frame_path)
            vid_frames.append(frame_data)
        data.append(vid_frames)
        labels.append(index)
        
X = np.array(data)
Y = to_categorical(labels).astype(int)

[[[ 0.          0.          0.         ...  0.          0.
    0.        ]
  [ 0.          0.          0.         ... -0.00472217 -0.00229955
    0.00864007]
  [ 0.          0.          0.         ... -0.02770293  0.04162392
   -0.06097721]
  ...
  [ 0.          0.          0.         ... -0.00812876 -0.00361145
    0.00348267]
  [ 0.          0.          0.         ... -0.00533987  0.01782294
    0.00547137]
  [ 0.          0.          0.         ... -0.08807975  0.03011333
    0.01060701]]

 [[ 0.          0.          0.         ...  0.          0.
    0.        ]
  [ 0.          0.          0.         ...  0.04938361  0.0405489
   -0.00897308]
  [ 0.          0.          0.         ...  0.04184568  0.01925379
    0.0832636 ]
  ...
  [ 0.          0.          0.         ... -0.00928868 -0.06482025
   -0.00362094]
  [ 0.          0.          0.         ...  0.05936194 -0.31114006
    0.32943937]
  [ 0.          0.          0.         ... -0.06199901  0.00791179
   -0.08963574]]

 [[ 0

In [4]:
to_categorical(labels).astype(int)

array([[1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1]], shape=(205, 5))

In [ ]:
X_train, X_val, Y_train, Y_val = train_test_split(X, 
                                                    Y, 
                                                    test_size=0.05,
                                                    random_state=42,    # Makes the split reproducible
                                                    shuffle=True)

[[0 0 0 0 1]
 [0 1 0 0 0]
 [0 0 0 0 1]
 [0 1 0 0 0]
 [0 0 0 1 0]
 [1 0 0 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 0 0 1 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [0 1 0 0 0]
 [0 0 0 1 0]
 [0 1 0 0 0]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [0 1 0 0 0]
 [0 0 0 0 1]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 1 0]
 [0 1 0 0 0]
 [0 0 0 1 0]
 [0 0 0 1 0]
 [0 0 0 1 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 1]
 [0 1 0 0 0]
 [0 0 0 1 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]

# Build LSTM

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

In [ ]:

# Layer 1
model = Sequential()

# Input: (20 frames, 21 points * 6 =  features)
model.add(LSTM(128, 
               return_sequences=True, 
               activation='tanh',
               input_shape=(20, 126), dropout=0.2))


model.add(LSTM(64,
               activation='tanh', 
               return_sequences=False, 
               dropout=0.2))

model.add(Dense(64, activation='relu'))
model.add(Dropout(0.3))

model.add(Dense(32, activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(len(label_map), activation='softmax'))

C:\Users\haivu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [9]:
model.compile(optimizer='Adam', 
              loss='categorical_crossentropy', 
              metrics=['categorical_accuracy'])
early_stopping = EarlyStopping(
    monitor='val_loss',
    patience=30,
    restore_best_weights=True,
    verbose=1
)

In [10]:
model.fit(X_train, 
          Y_train, 
          validation_data = (X_val, Y_val),
          epochs=300
          )

Epoch 1/300
7/7 ━━━━━━━━━━━━━━━━━━━━ 2s 63ms/step - categorical_accuracy: 0.2938 - loss: 1.4918 - val_categorical_accuracy: 0.4545 - val_loss: 1.3039
Epoch 2/300
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - categorical_accuracy: 0.3866 - loss: 1.3025 - val_categorical_accuracy: 0.5455 - val_loss: 1.1803
Epoch 3/300
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - categorical_accuracy: 0.3866 - loss: 1.2167 - val_categorical_accuracy: 0.3636 - val_loss: 1.1704
Epoch 4/300
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - categorical_accuracy: 0.4175 - loss: 1.1482 - val_categorical_accuracy: 0.3636 - val_loss: 1.1163
Epoch 5/300
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - categorical_accuracy: 0.4588 - loss: 1.0912 - val_categorical_accuracy: 0.5455 - val_loss: 1.0745
Epoch 6/300
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - categorical_accuracy: 0.4485 - loss: 1.1041 - val_categorical_accuracy: 0.5455 - val_loss: 1.0064
Epoch 7/300
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - categorical_accuracy: 0.5464 - loss: 1.0189 - va

In [ ]:
model.save('action.h5')

# load 
# model.load_weights('action.h5')